// Fetch movies
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export type FETCH_MOVIES_REQUEST = typeof FETCH_MOVIES_REQUEST;
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export type FETCH_MOVIES_SUCCESS = typeof FETCH_MOVIES_SUCCESS;
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export type FETCH_MOVIES_FAILURE = typeof FETCH_MOVIES_FAILURE;

// Search movies
export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export type SEARCH_MOVIES_REQUEST = typeof SEARCH_MOVIES_REQUEST;
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export type SEARCH_MOVIES_SUCCESS = typeof SEARCH_MOVIES_SUCCESS;
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE";
export type SEARCH_MOVIES_FAILURE = typeof SEARCH_MOVIES_FAILURE;
