// Fetch movie
export const FETCH_MOVIE_REQUEST = "FETCH_MOVIE_REQUEST";
export type FETCH_MOVIE_REQUEST = typeof FETCH_MOVIE_REQUEST;
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export type FETCH_MOVIE_SUCCESS = typeof FETCH_MOVIE_SUCCESS;
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";
export type FETCH_MOVIE_FAILURE = typeof FETCH_MOVIE_FAILURE;
